version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_BASE_URL=http://api:8080

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - minio
    environment:
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=myaccesskey
      - S3_SECRET_KEY=mysecretkey

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ROOT_USER: myaccesskey
      MINIO_ROOT_PASSWORD: mysecretkey
    volumes:
      - minio_data:/data

volumes:
  minio_data:
